name:  ezscrip
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <3.19.6"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  intl: any

  path_provider: ^2.1.3

  provider: ^6.1.2


  flutter_svg: ^2.0.10

  eva_icons_flutter: ^3.1.0

  global_configuration: ^2.0.0-nullsafety.1


  flutter_spinkit: ^5.2.1

  flutter_pdfview: ^1.3.2

  permission_handler: ^11.3.1 

  shared_preferences: ^2.2.3

  sembast: ^3.5.0

  enum_to_string: ^2.0.1

  double_back_to_close_app: ^2.0.0

  dropdown_button2: ^2.3.9

  toggle_switch: ^2.3.0
  
  animated_toggle_switch: ^0.8.2
  
  flutter_expanded_tile: ^0.3.7

  toast: ^0.3.0

  intl_utils: ^2.0.0

  pin_code_fields: ^8.0.1

  flutter_slidable: ^3.0.1

  flutter_vector_icons: ^2.0.0

  dots_indicator: ^3.0.0

  tokenizer: ^1.0.0

  count_stepper: ^0.0.4

  swipe_to: ^1.0.2

  printing: ^5.11.0

  pdf: ^3.0.0

  lint: ^2.1.2

  flutter_carousel_widget: ^2.0.4

  spinner_input_plus: ^0.0.1

  get_it: ^7.6.1

  watch_it: ^1.4.0
  
  flutter_typeahead: ^5.1.0

  sliding_up_panel: ^2.0.0

  scroll_date_picker: ^3.7.3

  flutter_holo_date_picker: ^1.1.3

  filter_list: ^1.0.2

  flutter_multi_formatter: ^2.12.4

  country_calling_code_picker: ^2.0.0
  
  rate_my_app: ^2.2.0

  flutter_secure_storage: 9.2.4

  no_context_navigation: ^3.0.0

  flash: ^3.0.5+2

  encrypt: ^5.0.0

  font_awesome_flutter: ^10.7.0

  awesome_notifications: ^0.8.2
  
  flutter_svg_provider: ^1.0.6

  scrollable_positioned_list: ^0.3.8

  scrollview_observer: ^1.20.0


  flutter_localized_locales: any

  validatorless : 1.2.3

  bottom_sheet: ^4.0.0

  workmanager: ^0.5.2

  talker_flutter: ^4.2.3

  newrelic_mobile: 1.0.9

  auto_size_text: ^3.0.0
  
  flutter_timeline: ^0.3.0
  
  scroll_to_index: ^3.0.1

  scroll_pos: ^0.5.0

  jiffy : ^6.2.1
  
  flutter_advanced_switch: ^3.0.1

  state_notifier: ^1.0.0

  time_picker_sheet: ^0.0.2+1

  hand_signature: ^3.0.1
    
  timeline_tile: 2.0.0

  timelines: ^0.1.0

  sentry_flutter: ^8.2.0
  
  rect_getter: ^1.1.0

  slide_switcher: ^1.1.2

  device_info_plus: ^10.1.0
  
  share_plus: ^9.0.0

  super_tooltip: ^2.0.8

  accessibility_tools: ^2.0.0

  flutter_spinbox: ^0.13.1

  icons_launcher: ^2.0.4

  flutter_native_splash: ^2.4.0

  animated_custom_dropdown: ^3.0.0

  ensure_visible_when_focused: ^1.2.0

  skeletonizer: ^1.3.0

  shimmer: ^3.0.0

  platform_info: ^4.0.2

  patrol_cli: ^2.7.0

  
dev_dependencies:
 
  build_runner: ^2.3.3
  
  patrol: ^3.5.1

  integration_test:
    sdk: flutter
  
  flutter_test:
    sdk: flutter

  test: any
  flutter_lints: ^4.0.0

  
  
  
icons_launcher:
  image_path: "assets/images/healthcare-icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/healthcare-icon.png"
      # adaptive_background_color: '#ffffff'
     
    ios:
      enable: true
      image_path: "assets/images/healthcare-icon.png"
   
    macos:
      enable: false
      image_path: "assets/healthcare-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true   
  assets:
    - assets/l10n/intl_en.arb
    - assets/cfg/app_settings.json
    - assets/demo/test_data_demo.json
    - assets/test/test_data_profile.json
    - assets/test/test_data_profile_1.json
    - assets/test/test_data_consultation.json
    - assets/test/test_data_consultation.json
    - assets/test/test_data_consultation_1.json
    - assets/test/test_data_consultation_2.json
    - assets/test/test_data_consultation_3.json
    - assets/test/test_data_consultation_4.json
    - assets/test/test_data_consultation_5.json
    - assets/test/test_data_consultation_search.json
    - assets/test/test_data_consultation_search_1.json
    - assets/cfg/languages_names.json
    - assets/cfg/medical_properties.json
    - assets/cfg/specialities.json
    - assets/medical.txt
    - assets/diseases.txt
    - assets/testparameters.txt
    - assets/images/bloodpressure.svg
    - assets/images//temperature.svg
    - assets/images/medical-test.svg
    - assets/images/spo2.svg
    - assets/images/line.svg
    - assets/images/consultation.svg
    - assets/images/vital_signs.svg
    - assets/images/prescription.svg
    - assets/images/user-preferences.svg
    - assets/images/ointment.svg
    - assets/images/person.svg
    - assets/images/human_body.svg
    - assets/images/note.svg
    - assets/images/note-sticky.svg
    - assets/images/daybreak.svg
    - assets/images/morning.svg
    - assets/images/afternoon.svg
    - assets/images/evening.svg
    - assets/images/night.svg
    - assets/images/clinic.svg
    - assets/images/circle.svg
    - assets/images/hr.svg
    - assets/images/healthcare-icon.png
    - assets/images/phone.svg
    - assets/images/medical_history.svg
    - assets/images/medical_history1.svg
    - assets/images/medical-history2.svg
    - assets/images/formats/1.png
    - assets/images/formats/2.png
    - assets/images/templates/letterhead_blank.jpg
    - assets/images/log_file.svg
    - assets/demo/demo.pdf
    - assets/images/chevron_left.svg
    - assets/images/chevron_left_bold.svg
    - assets/images/tests.svg
    - assets/images/specialities/body.svg
    - assets/images/specialities/tooth.svg
    - assets/images/specialities/cardiology.svg
    - assets/images/specialities/ears_nose_and_throat.svg
    - assets/images/specialities/endocrinology.svg
    - assets/images/specialities/gastroenterology.svg
    - assets/images/specialities/gynecology.svg
    - assets/images/specialities/hepatology.svg
    - assets/images/specialities/obstetricsmonia.svg
    - assets/images/specialities/oncology.svg
    - assets/images/specialities/opthalmology.svg
    - assets/images/specialities/orthopaedics.svg
    - assets/images/specialities/gastroenterology.svg
    - assets/images/specialities/hepatology.svg
    - assets/images/specialities/psychology.svg
    - assets/images/specialities/radiology.svg
    - assets/images/specialities/urology.svg
    - assets/images/specialities/respirology.svg
    - assets/images/specialities/hepatology.svg
    - assets/images/specialities/geriatrics.svg
    - assets/images/specialities/nephrology.svg
    - assets/images/specialities/rheumatology.svg 
    - assets/images/specialities/pharmacy.svg
    - assets/images/specialities/baby_0203m.svg
    - assets/images/specialities/joints.svg
    - assets/images/specialities/nerve.svg
    - assets/images/specialities/neurology.svg
    - assets/images/specialities/skeleton.svg

 
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

patrol:
  app_name: ezscrip App
  android:
    package_name: com.example.ezscrip
  ios:
    bundle_id: com.example.ezscrip

# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  # Generates files with given ignore rules for file.
  # ignored_rules:
  #   - public_member_api_docs
  # Generates dart font family references for fonts specified in pubspec.yaml
  # fonts: true
  # -------- OR --------
  # fonts:
  #   class_name: MyFonts
  #   file_name: my_fonts
  # Location where all the generated references will be stored
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp, .svg ]
   